import Head from 'next/head';

import FilterBar from '../components/SearchBar';
import Countries from '../components/Countries';

export default function Home() {
  return (
    <div className="flex flex-col gap-10">
      <Head>
        <title>Countries of the world</title>
        <meta name="description" content="Results generated by the countries API" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <FilterBar />
      <Countries />
    </div>
  );
}
